import { RecyclingData } from './types';

export const CITY_RULES: RecyclingData = {
  vienna: {
    name: "Wien",
    bins: {
      plastic: { name: "Gelbe Tonne (Plastic/Metal)", color: "bg-yellow-400" },
      paper: { name: "Altpapier (Paper)", color: "bg-red-500" },
      glass: { name: "Glas (Glass)", color: "bg-green-500" },
      bio: { name: "Biotonne (Organic)", color: "bg-amber-700" },
      rest: { name: "Restmüll (Residual)", color: "bg-gray-800" }
    },
    mappings: {
      "banana": ["bio"],
      "apple": ["bio"],
      "granny smith": ["bio"],
      "orange": ["bio"],
      "lemon": ["bio"],
      "newspaper": ["paper"],
      "magazine": ["paper"],
      "packet": ["paper"],
      "cardboard": ["paper"],
      "carton": ["paper"],
      "plastic bottle": ["plastic"],
      "water bottle": ["plastic"],
      "pop bottle": ["plastic"],
      "soda bottle": ["plastic"],
      "pill bottle": ["plastic"],
      "beer bottle": ["glass"],
      "wine bottle": ["glass"],
      "soda can": ["plastic"],
      "can": ["plastic"],
      "yogurt cup": ["plastic"],
      "diaper": ["rest"],
      "tissue": ["rest"],
      "pizza box (clean)": ["paper"],
      "pizza box (dirty)": ["rest"],
      "pizza box": ["rest"],
      "espresso": ["rest"],
      "coffee mug": ["rest"],
      "cup": ["rest"]
    }
  },
  graz: {
    name: "Graz",
    bins: {
      plastic: { name: "Gelber Sack (Plastic)", color: "bg-yellow-400" },
      metal: { name: "Dosen (Metal)", color: "bg-blue-500" },
      paper: { name: "Altpapier (Paper)", color: "bg-red-500" },
      bio: { name: "Bioabfall (Organic)", color: "bg-amber-700" },
      rest: { name: "Restmüll (Residual)", color: "bg-gray-800" }
    },
    mappings: {
      "banana": ["bio"],
      "apple": ["bio"],
      "soda can": ["metal"],
      "can": ["metal"],
      "plastic bottle": ["plastic"],
      "water bottle": ["plastic"],
      "pop bottle": ["plastic"],
      "yogurt cup": ["plastic"],
      "newspaper": ["paper"],
      "beer bottle": ["rest"], 
      "wine bottle": ["rest"],
      "glass": ["rest"],
      "pizza box (clean)": ["paper"],
      "pizza box (dirty)": ["rest"]
    }
  },
  linz: {
    name: "Linz",
    bins: {
      plastic: { name: "Gelber Sack (Plastic & Metal Packaging)", color: "bg-yellow-400" },
      paper: { name: "Altpapier (Paper)", color: "bg-red-500" },
      glass: { name: "Altglas (Glass)", color: "bg-green-500" },
      bio: { name: "Biotonne (Organic)", color: "bg-amber-700" },
      rest: { name: "Restmüll (Residual)", color: "bg-gray-800" },
      asz: { name: "Altstoffsammelzentrum (ASZ)", color: "bg-orange-500", description: "Recycling Center" }
    },
    mappings: {
      "pizza box (clean)": ["paper"],
      "pizza box (dirty)": ["rest"],
      "pizza box (greasy)": ["rest"],

      "plastic bottle": ["plastic"],
      "water bottle": ["plastic"],
      "pop bottle": ["plastic"],
      "soda bottle": ["plastic"],
      "soda can": ["plastic"],
      "aluminum can": ["plastic"],
      "can": ["plastic"],
      "newspaper": ["paper"],
      "magazine": ["paper"],
      "cardboard": ["paper"],
      "banana": ["bio"],
      "apple": ["bio"],
      "fruit": ["bio"],
      "glass bottle": ["glass"],
      "wine bottle": ["glass"],
      "beer bottle": ["glass"],
      "diaper": ["rest"],
      "cigarette": ["rest"],
      "yogurt cup": ["plastic"],
      "tetra pak": ["plastic"],
      "milk carton": ["plastic"],

      "lipsticks": ["asz"],
      "solvents": ["asz"],
      "solder": ["asz"],
      "balloons": ["rest"],
      "air filters": ["rest"],
      "air mattresses": ["rest"],
      "air pumps (plastic)": ["rest"],
      "air pumps (metal)": ["asz"],
      "rags": ["rest"],
      "cornstarch chips": ["rest"],
      "cornstarch cutlery, dishes": ["bio"],
      "cornstarch bags": ["bio"],
      "margarine tubs": ["plastic", "asz"],
      "jam tubs (plastic)": ["plastic", "asz"],
      "jam jars (empty)": ["asz", "glass"],
      "wire mesh": ["asz"],
      "chain-link fences": ["asz"],
      "machine parts (metal)": ["asz"],
      "massage oils": ["asz"],
      "mattresses": ["asz"],
      "wall demolition waste": ["asz"],
      "mouse traps": ["rest"],
      "mouse poison": ["asz"],
      "medicines": ["asz"],
      "medicine bottles (glass, empty)": ["asz", "glass"],
      "medicine packaging (plastic, blister, empty)": ["plastic", "asz"],
      "medicine packaging (paper/cardboard, empty)": ["asz", "paper"],
      "reusable tableware (aluminum, tin, enamel, stainless steel)": ["asz"],
      "reusable tableware (glass, ceramic, plastic)": ["asz"],
      "knives": ["asz"],
      "brass parts": ["asz"],
      "metal gutters": ["asz"],
      "metal pipes": ["asz"],
      "metalworking oils": ["asz"],
      "metal lids from packaging": ["plastic", "asz"],
      "metal drums (packaging)": ["plastic", "asz"],
      "metal drums (non-packaging)": ["asz"],
      "metal foils (packaging)": ["plastic", "asz"],
      "metal canisters (empty)": ["plastic", "asz"],
      "metal foil from champagne bottles": ["plastic", "asz"],
      "metal polishes": ["asz"],
      "metal packaging (empty)": ["plastic", "asz"],
      "microwaves": ["asz"],
      "milk bottles (plastic, empty)": ["asz"],
      "dairy products (spoiled)": ["bio"],
      "dairy product packaging (plastic)": ["plastic", "asz"],
      "mineral oil cans (with residue)": ["asz"],
      "mineral oil cans (empty)": ["asz"],
      "mineral oils": ["asz"],
      "rags soaked in mineral oil": ["asz"],
      "objects soiled with mineral oil": ["asz"],
      "soil contaminated with mineral oil": ["asz"],
      "mineral wool": ["asz"],
      "concrete mixers": ["asz"],
      "furniture": ["asz"],
      "furniture polish": ["asz"],
      "assembly foam cans (with residue)": ["asz"],
      "assembly foams, cfc-containing (cured)": ["asz"],
      "assembly foams, cfc-free (cured)": ["rest"],
      "mortar": ["asz"],
      "motor oils": ["asz"],
      "moth repellents": ["asz"],
      "mouse pads": ["rest"],
      "mulch films": ["rest"],
      "gauze bandages": ["rest"],
      "garbage bags": ["rest"],
      "oral care products": ["asz"],
      "face masks, disposable masks": ["rest"],
      "ammunition": ["asz"],
      "coin boxes": ["rest"],
      "mussel shells": ["rest"],
      "musical instruments (metal)": ["asz"],
      "musical instruments (electronic)": ["asz"],
      "musical instruments (non-metal)": ["rest"],
      "music cassettes": ["rest"],
      "night storage heaters": ["asz"],
      "nail polish (cured)": ["rest"],
      "nail polish (liquid)": ["asz"],
      "nail polish remover": ["asz"],
      "nail polish bottles (with residue)": ["asz"],
      "sewing waste": ["rest"],
      "sewing machines": ["asz"],
      "sewing needles": ["asz"],
      "photo negatives": ["rest"],
      "neon tubes": ["asz"],
      "nespresso capsules (aluminum)": ["asz"],
      "nets as packaging (fruit/veg, christmas trees)": ["plastic", "asz"],
      "nets as packaging (biodegradable)": ["plastic", "asz"],
      "non-ferrous metals": ["asz"],
      "sneezing powder": ["rest"],
      "nitro thinners": ["asz"],
      "nut shells and fruit pits": ["bio"],
      "fruit/vegetable crates (wood, non-packaging)": ["asz"],
      "fruit/vegetable crates (plastic, non-packaging)": ["asz"],
      "fruit waste": ["bio"],
      "fruit nets (non-biodegradable)": ["plastic", "asz"],
      "fruit punnets (cardboard, clean)": ["asz", "paper"],
      "fruit punnets (plastic)": ["plastic", "asz"],
      "stoves/ovens (e.g. electric)": ["asz"],
      "stove pipes": ["asz"],
      "oil binders (used)": ["asz"],
      "oil filters": ["asz"],
      "oil radiators (electric)": ["asz"],
      "opaque glass bottles": ["asz", "glass"],
      "orange peels": ["bio"],
      "organic waste": ["bio"],
      "easter grass": ["rest"],
      "overhead transparencies": ["rest"],
      "wrapping paper": ["asz", "paper"],
      "warning triangles (iron)": ["asz"],
      "warning triangles (plastic)": ["rest"],
      "warning triangle cases": ["asz"],
      "paper (waxed or soiled)": ["rest"],
      "paper (clean, uncoated)": ["asz", "paper"],
      "paper as packaging (foil-coated)": ["plastic", "asz"],
      "shredded paper": ["asz", "paper"],
      "paper (non-packaging, foil-coated)": ["rest"],
      "paper towels (soiled or clean)": ["rest"],
      "paper scraps": ["asz", "paper"],
      "paper bags for organic waste": ["bio"],
      "paper napkins": ["rest"],
      "paper tissues": ["rest"],
      "paper cups for drinks": ["plastic", "asz"],
      "paper plates (clean, uncoated)": ["asz", "paper"],
      "paper plates (soiled)": ["rest"],
      "perfumes (with residue)": ["asz"],
      "perfume bottles (glass, empty)": ["asz", "glass"],
      "perfume bottles (ceramic or plastic, empty)": ["plastic", "asz"],
      "parquet flooring": ["asz"],
      "pellets": ["rest"],
      "furs (unwearable, soiled)": ["rest"],
      "furs (wearable, clean)": ["rest", "asz"],
      "petroleum": ["asz"],
      "plant nursery trays (plastic)": ["plastic", "asz"],
      "pesticides": ["asz"],
      "photovoltaic modules (silicon-based)": ["asz"],
      "fungicides/mushroom poisons": ["asz"],
      "brushes": ["rest"],
      "brush cleaners": ["asz"],
      "pistols": ["asz"],
      "pizza boxes (soiled/greasy)": ["rest"],
      "plastic objects (non-packaging)": ["rest"],
      "plastic buckets (soiled)": ["rest"],
      "plastic buckets (packaging)": ["plastic", "asz"],
      "plastic buckets (non-packaging)": ["asz"],
      "plastic bowls (packaging/household)": ["asz"],
      "plastic bowls (packaging)": ["plastic", "asz"],
      "plastic bowls (household)": ["rest"],
      "circuit boards": ["asz"],
      "plexiglass": ["rest"],
      "polaroid photos": ["rest"],
      "polaroid cartridges": ["rest"],
      "cushions": ["rest"],
      "upholstered furniture": ["asz"],
      "pomades": ["asz"],
      "porcelain bottles (packaging)": ["plastic", "asz"],
      "post-it notes": ["asz", "paper"],
      "postcards": ["asz", "paper"],
      "condoms": ["rest"],
      "chipboard": ["asz"],
      "hazardous waste": ["asz"],
      "pu foam cans (with residue)": ["asz"],
      "pu foam cans (metal, empty)": ["plastic", "asz"],
      "pu foams (cured)": ["rest"],
      "pump sprays (plastic, empty)": ["plastic", "asz"],
      "dolls": ["rest"],
      "dollhouses": ["asz"],
      "dry cleaner bags": ["plastic", "asz"],
      "cleaning rags": ["rest"],
      "cleaning agents (with residue)": ["asz"],
      "cleaning cloth": ["rest"],
      "pv modules (silicon-based)": ["asz"],
      "pvc waste (e.g. flooring)": ["rest"],
      "pvc gutters": ["asz"],
      "pvc pipes": ["asz"],
      "mercury": ["asz"],
      "mercury-containing lamps": ["asz"],
      "mercury switches": ["asz"],
      "erasers": ["rest"],
      "radios": ["asz"],
      "crinkle film": ["plastic", "asz"],
      "lawnmowers": ["asz"],
      "grass clippings": ["bio"],
      "turf/sod": ["asz"],
      "razor blades": ["asz"],
      "shaving brushes": ["rest"],
      "rattan shopping baskets": ["asz"],
      "rat traps": ["rest"],
      "rat poison": ["asz"],
      "room spray cans (with residue)": ["asz"],
      "rain barrels (plastic)": ["asz"],
      "rain barrels (metal)": ["asz"],
      "residual waste": ["rest"],
      "drywall/gypsum boards": ["asz"],
      "bark": ["bio"],
      "ring binders (plastic)": ["rest"],
      "ring binders (paper/cardboard, metal removed)": ["asz", "paper"],
      "ring binders (paper/cardboard, with metal)": ["rest"],
      "x-rays": ["asz"],
      "rust protection agents": ["asz"],
      "routers": ["asz"],
      "soot": ["rest"],
      "seed dressings": ["asz"],
      "seed bags (paper, empty)": ["asz", "paper"],
      "biodegradable bags (e.g. cornstarch)": ["bio"],
      "plastic bags": ["plastic", "asz"],
      "paper bags (clean)": ["asz", "paper"],
      "paper bags (soiled)": ["rest"],
      "sawdust (treated wood)": ["rest"],
      "sawdust (untreated wood)": ["bio"],
      "ointment jars (glass, empty)": ["asz", "glass"],
      "ointment jars (plastic, empty)": ["plastic", "asz"],
      "ointment tubes (plastic, empty)": ["plastic", "asz"],
      "ointment tubes (metal, empty)": ["plastic", "asz"],
      "sand": ["asz"],
      "sanitary fixtures (ceramic)": ["asz"],
      "sanitary fixtures (plastic)": ["asz"],
      "sanitary cleaners": ["asz"],
      "satellite dishes": ["asz"],
      "sauerkraut packaging": ["plastic", "asz"],
      "acids": ["asz"],
      "boxes": ["asz", "paper"],
      "citrus fruit peels": ["bio"],
      "vinyl records": ["rest"],
      "record sleeves (paper)": ["asz", "paper"],
      "shuttering panels": ["asz"],
      "fireclay": ["asz"],
      "foam rubber/foam (packaging)": ["plastic", "asz"],
      "foam rubber/foam (non-packaging)": ["rest"],
      "credit/bank cards": ["rest"],
      "wheelbarrow (iron)": ["asz"],
      "wheelbarrow (plastic)": ["asz"],
      "scissors": ["asz"],
      "scouring powder cans": ["asz"],
      "ham nets": ["rest"],
      "ham foils/paper": ["plastic", "asz"],
      "umbrellas": ["rest"],
      "umbrella stands (wood)": ["asz"],
      "umbrella stands (metal)": ["asz"],
      "umbrella stands (non-metal)": ["rest"],
      "whipped cream/soda chargers (empty)": ["plastic", "asz"],
      "whipped cream cups": ["plastic", "asz"],
      "inflatable boats": ["rest"],
      "sandpaper": ["rest"],
      "keys": ["asz"],
      "lubricants (mineral)": ["asz"],
      "jewelry boxes": ["rest"],
      "snail poison": ["asz"],
      "tailoring waste": ["rest"],
      "cut flowers": ["bio"],
      "sewing patterns": ["asz", "paper"],
      "pacifiers": ["rest"],
      "snuff tobacco": ["bio"],
      "cords/strings": ["rest"],
      "chocolate wrappers": ["asz", "paper"],
      "protective covers": ["rest"],
      "metal ladles": ["asz"],
      "writing paper": ["asz", "paper"],
      "writing inks": ["rest"],
      "shotgun pellets": ["asz"],
      "scrap metal": ["asz"],
      "shrink wrap (clean)": ["plastic", "asz"],
      "shrink wrap (soiled)": ["rest"],
      "shoelaces": ["rest"],
      "shoe polish tins (metal, empty)": ["plastic", "asz"],
      "shoe polishes/sprays": ["asz"],
      "shoe polish tubes (plastic)": ["plastic", "asz"],
      "shoes (unwearable)": ["rest"],
      "shoes (wearable, clean)": ["asz"],
      "shoe soles": ["rest"],
      "school bags": ["rest"],
      "sponges": ["rest"],
      "welding electrodes": ["rest"],
      "welding machines": ["asz"],
      "swords": ["asz"],
      "swim fins/wings": ["rest"],
      "tissue paper": ["asz", "paper"],
      "soap/shampoo bottles (plastic, empty)": ["plastic", "asz"],
      "soap remnants": ["rest"],
      "ropes": ["rest"],
      "mustard jars (empty)": ["asz", "glass"],
      "mustard tubes (with residue)": ["rest"],
      "mustard tubes (plastic)": ["plastic", "asz"],
      "mustard tubes (metal, empty)": ["plastic", "asz"],
      "electronic fuses": ["asz"],
      "silicate plasters": ["asz"],
      "silicone cartridges (with residue)": ["asz"],
      "silicone cartridges (empty)": ["plastic", "asz"],
      "sofa sets": ["asz"],
      "sofa sets (aluminum)": ["asz"],
      "sofa sets (iron)": ["asz"],
      "sofa sets (wood)": ["asz"],
      "sofa sets (plastic/textile)": ["asz"],
      "skis/snowboards": ["asz"],
      "ski boots": ["rest"],
      "ski poles": ["asz"],
      "panty liners": ["rest"],
      "solar lights": ["asz"],
      "solar cells": ["asz"],
      "pretzel stick bags": ["plastic", "asz"],
      "sun oils/creams": ["rest"],
      "fillers (plaster/cement base)": ["asz"],
      "fillers (resin base, cured)": ["rest"],
      "fillers (resin base, not cured)": ["asz"],
      "cooking oil cans (metal, empty)": ["plastic", "asz"],
      "cooking oil bottles (glass, empty)": ["asz", "glass"],
      "cooking oil bottles (plastic, empty)": ["plastic", "asz"],
      "food scraps": ["bio"],
      "bulky waste": ["asz"],
      "mirror glass": ["asz"],
      "mirror glass (small quantities)": ["rest"],
      "playing cards": ["asz", "paper"],
      "game consoles": ["asz"],
      "toys (plastic or metal)": ["rest"],
      "sports equipment": ["rest"],
      "sport bows": ["asz"],
      "spray cans (with residue)": ["asz"],
      "spray cans (plastic, empty)": ["plastic", "asz"],
      "spray cans (metal, empty)": ["plastic", "asz"],
      "explosives": ["asz"],
      "pesticides/sprays": ["asz"],
      "pesticide containers (with residue)": ["asz"],
      "pesticide containers (plastic, empty)": ["plastic", "asz"],
      "cistern additives": ["asz"],
      "cardboard cores (paper towels/toilet paper)": ["asz", "paper"],
      "cardboard cores (carpet)": ["asz", "paper"],
      "dishwashing liquid": ["asz"],
      "dishwashing liquid bottles (plastic, empty)": ["plastic", "asz"],
      "hand blenders": ["asz"],
      "tinfoil": ["plastic", "asz"],
      "vacuum cleaners": ["asz"],
      "vacuum cleaner bags (full)": ["rest"],
      "power sockets": ["rest"],
      "floor lamps": ["asz"],
      "stones": ["asz"],
      "stoneware bottles (packaging)": ["plastic", "asz"],
      "stoneware dishes": ["asz"],
      "hard coal, coke": ["rest"],
      "stamps": ["rest"],
      "stamp inks/pads": ["asz"],
      "stereo systems": ["asz"],
      "sparklers (burnt)": ["rest"],
      "sparklers (unburnt)": ["asz"],
      "cloth handkerchiefs": ["rest"],
      "fabric scraps": ["rest"],
      "cloth bags (packaging)": ["plastic", "asz"],
      "stuffed animals": ["rest"],
      "shrub clippings (shredded)": ["bio"],
      "matches": ["rest"],
      "grit/sand": ["asz"],
      "straws": ["rest"],
      "straw hats": ["rest"],
      "tights (torn)": ["rest"],
      "crash helmets": ["rest"],
      "styrofoam packaging": ["plastic", "asz"],
      "styrofoam chips (packaging)": ["plastic", "asz"],
      "soup bags": ["plastic", "asz"],
      "tablets": ["asz"],
      "tampons": ["rest"],
      "wallpapers": ["rest"],
      "bags (plastic or leather)": ["rest"],
      "bags (plastic or leather, functional)": ["asz"],
      "flashlights": ["asz"],
      "calculators": ["asz"],
      "tea bags (plastic)": ["rest"],
      "tea bags (paper/organic)": ["bio"],
      "tar residues": ["asz"],
      "tar paper": ["asz"],
      "pasta bags": ["plastic", "asz"],
      "phone books": ["asz", "paper"],
      "phone cards": ["rest"],
      "tennis balls": ["rest"],
      "tennis rackets": ["rest"],
      "carpets": ["asz"],
      "turpentine": ["asz"],
      "textile packaging": ["plastic", "asz"],
      "hot water bottles": ["rest"],
      "thermometers (electronic)": ["asz"],
      "thermometers (mercury)": ["asz"],
      "thermal paper (receipts)": ["rest"],
      "thermos flasks": ["rest"],
      "freezer bags (empty)": ["plastic", "asz"],
      "frozen food packaging (cardboard)": ["asz", "paper"],
      "frozen food packaging (composite)": ["plastic", "asz"],
      "animal bristles (natural)": ["bio"],
      "pet food": ["bio"],
      "pet food cans/trays (empty)": ["plastic", "asz"],
      "animal carcasses": ["asz"],
      "taxidermy animals": ["asz"],
      "ink erasers": ["rest"],
      "ink cartridges (empty)": ["plastic", "asz"],
      "ink cartridges (full)": ["rest"],
      "correction fluid (solvent-based)": ["asz"],
      "table linen": ["rest"],
      "toasters": ["asz"],
      "audio tapes/cassettes": ["rest"],
      "toners": ["asz"],
      "toner containers (empty)": ["asz"],
      "toner cartridges": ["asz"],
      "clay pots": ["asz"],
      "earthenware": ["asz"],
      "pots and pans (metal)": ["asz"],
      "curd/quark tubs": ["asz"],
      "potted plants (without pot)": ["bio"],
      "carrier bags (plastic)": ["plastic", "asz"],
      "carrier bags (paper)": ["asz", "paper"],
      "fuels": ["asz"],
      "fuel filters": ["asz"],
      "drinking bottles (plastic)": ["asz", "rest"],
      "drinking glasses": ["asz"],
      "drinking straws": ["rest"],
      "dried flowers": ["bio"],
      "hair dryers (hood)": ["asz"],
      "tubes (plastic, empty)": ["plastic", "asz"],
      "tubes (plastic/metal, with residue)": ["plastic", "asz"],
      "tubes (metal, empty)": ["plastic", "asz"],
      "duvets": ["rest"],
      "doors/frames (metal)": ["asz"],
      "clocks (digital)": ["asz"],
      "clocks (mechanical)": ["rest"],
      "watch cases": ["rest"],
      "weeds": ["bio"],
      "underbody protection": ["asz"],
      "consumer electronics": ["asz"],
      "usb sticks, hard drives": ["asz"],
      "uv lamps": ["asz"],
      "vases (plastic, glass)": ["rest"],
      "fans": ["asz"],
      "bandages": ["rest"],
      "combustion engines (empty)": ["asz"],
      "laminated glass": ["asz"],
      "extension cables": ["asz"],
      "packaging (glass, empty)": ["asz", "glass"],
      "packaging (paper)": ["asz", "paper"],
      "packaging bottles (plastic, empty)": ["plastic", "asz"],
      "packaging fleece": ["plastic", "asz"],
      "caps/lids (plastic)": ["plastic", "asz"],
      "caps/lids (metal)": ["plastic", "asz"],
      "sealing varnishes": ["asz"],
      "power strips": ["asz"],
      "video cassettes": ["rest"],
      "video cassette cases (plastic)": ["rest"],
      "video cassette cases (paper)": ["asz", "paper"],
      "vcrs": ["asz"],
      "bird cages": ["asz"],
      "curtains": ["asz"],
      "curtain rails": ["asz"],
      "wax crayons": ["rest"],
      "wax crayons (metal box)": ["plastic", "asz"],
      "wax paper": ["rest"],
      "weapons": ["asz"],
      "hiking map covers": ["rest"],
      "heat pumps": ["asz"],
      "insulated bags (for grilled food)": ["plastic", "asz"],
      "washbasins": ["asz"],
      "white spirit": ["asz"],
      "clothespins": ["rest"],
      "laundry baskets": ["asz"],
      "clotheslines": ["rest"],
      "clothes racks": ["asz"],
      "tumble dryers": ["asz"],
      "washing machines": ["asz"],
      "detergents": ["asz"],
      "detergent dosing aids (plastic)": ["rest"],
      "detergent bottles (plastic)": ["plastic", "asz"],
      "detergent boxes (empty)": ["asz", "paper"],
      "kettles": ["asz"],
      "cotton balls/pads": ["rest"],
      "cotton swabs": ["rest"],
      "toilet bowls": ["asz"],
      "toilet cleaners": ["asz"],
      "fabric softeners": ["asz"],
      "fabric softener bottles (plastic)": ["plastic", "asz"],
      "electric fence insulators": ["rest"],
      "wine boxes": ["asz", "paper"],
      "tinplate cans (empty)": ["plastic", "asz"],
      "tinplate": ["asz"],
      "corrugated iron": ["asz"],
      "corrugated cardboard": ["asz", "paper"],
      "advertising brochure bags (empty)": ["plastic", "asz"],
      "toolboxes (plastic or metal)": ["asz"],
      "stretch wrap": ["asz"],
      "diaper pants": ["rest"],
      "diapers (reusable)": ["rest"],
      "diapers (disposable)": ["rest"],
      "wool remnants": ["rest"],
      "vole bait": ["asz"],
      "medical benzine": ["asz"],
      "sausage foils/paper": ["plastic", "asz"],
      "sausage skins": ["rest"],
      "tree stumps": ["asz"],
      "aerated concrete blocks": ["asz"],
      "toothbrushes": ["rest"],
      "electric toothbrushes": ["asz"],
      "toothpaste tubes (plastic)": ["plastic", "asz"],
      "toothpaste tubes (metal, empty)": ["plastic", "asz"],
      "toothpaste tubes (full)": ["rest"],
      "drawing paper": ["asz", "paper"],
      "magazines": ["asz", "paper"],
      "newspapers": ["asz", "paper"],
      "cellophane foils": ["plastic", "asz"],
      "cement": ["asz"],
      "cement bags (empty)": ["asz", "paper"],
      "bricks": ["asz"],
      "cigarette ash": ["rest"],
      "cigarette packs (with foil)": ["plastic", "asz"],
      "cigarette packs (without foil)": ["asz", "paper"],
      "houseplants (without pot)": ["bio"],
      "tin and zinc products": ["asz"],
      "pewter dishes": ["asz"],
      "lemon peels": ["bio"],
      "citrus fruits": ["bio"],
      "candy wrappers": ["plastic", "asz"],
      "spark plugs": ["rest"],
      "branches (shredded)": ["bio"],
      "thread remnants": ["rest"],
      "thread spools": ["rest"]
    }
  },
  salzburg: {
    name: "Salzburg",
    bins: {
      plastic: { name: "Gelber Sack", color: "bg-yellow-400" },
      paper: { name: "Altpapier", color: "bg-red-500" },
      bio: { name: "Bio", color: "bg-amber-700" },
      rest: { name: "Restmüll", color: "bg-gray-800" }
    },
    mappings: {
      "plastic bottle": ["plastic"],
      "water bottle": ["plastic"],
      "newspaper": ["paper"]
    }
  }
};

export const CITIES = Object.keys(CITY_RULES).map(key => ({
  id: key,
  name: CITY_RULES[key].name
}));